### PR TITLE
[prod] bkn-loans

### PR DESCRIPTION
**Pull request by marcoayamada**

### CODE REVIEW

**Comment by marcoayamada** [comment]
atlantis plan -p banking/emprestimo/production

**Comment by marcoayamada** [comment]
Ran Plan for dir: `subscriptions/banking/emprestimo` workspace: `production`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis/bin/terraform1.1.5 plan -input=false -refresh -out \"/atlantis/repos/marcoayamada/terraform-test/51/production/subscriptions/banking/emprestimo/banking::emprestimo::production-production.tfplan\" -var-file=prod.tfvars -var subscription_prod=${SUBS_SELECTED}" in "/atlantis/repos/marcoayamada/terraform-test/51/production/subscriptions/banking/emprestimo": exit status 1
Remote path --> subscriptions/banking/emprestimo

module.rg.azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/6e754131-54cf-4f48-853f-26acb5e6f5ab/resourceGroups/rg-terraform-prod]
╷
│ Error: reading resource group: resources.GroupsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '20d379f6-54f5-4aae-9421-d2ff430968f7' with object id '20d379f6-54f5-4aae-9421-d2ff430968f7' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/97e23b6a-9832-490d-933a-c6294936b304/resourcegroups/rg-terraform-prod' or the scope is invalid. If access was recently granted, please refresh your credentials."
╷
│ Warning: Provider azurerm is undefined
│ 
│   with module.rg.azurerm_resource_group.rg,
│ 
│   on main.tf line 4, in module "rg":
│   on ../../../modules/resource-group/main.tf line 1, in resource "azurerm_resource_group" "rg":
│    1: resource "azurerm_resource_group" "rg" {
│    4:   providers = { azurerm = azurerm.banking-emprestimo }
│ 
│ 
╵
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

```
</details>

**Comment by marcoayamada** [comment]
atlantis plan -p banking/emprestimo/production

**Comment by marcoayamada** [comment]
Ran Plan for dir: `subscriptions/banking/emprestimo` workspace: `production`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/atlantis/bin/terraform1.1.5 plan -input=false -refresh -out \"/atlantis/repos/marcoayamada/terraform-test/51/production/subscriptions/banking/emprestimo/banking::emprestimo::production-production.tfplan\" -var-file=prod.tfvars -var subscription_prod=${SUBS_SELECTED}" in "/atlantis/repos/marcoayamada/terraform-test/51/production/subscriptions/banking/emprestimo": exit status 1
Remote path --> subscriptions/banking/emprestimo

module.rg.azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/6e754131-54cf-4f48-853f-26acb5e6f5ab/resourceGroups/rg-terraform-prod]
╷
│ Error: reading resource group: resources.GroupsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '20d379f6-54f5-4aae-9421-d2ff430968f7' with object id '20d379f6-54f5-4aae-9421-d2ff430968f7' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/97e23b6a-9832-490d-933a-c6294936b304/resourcegroups/rg-terraform-prod' or the scope is invalid. If access was recently granted, please refresh your credentials."
╷
│ Warning: Provider azurerm is undefined
│ 
│   with module.rg.azurerm_resource_group.rg,
│ 
│   on main.tf line 4, in module "rg":
│   on ../../../modules/resource-group/main.tf line 1, in resource "azurerm_resource_group" "rg":
│    1: resource "azurerm_resource_group" "rg" {
│    4:   providers = { azurerm = azurerm.banking-emprestimo }
│ 
│ 
╵
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

```
</details>

**Comment by marcoayamada** [comment]
atlantis plan -p banking/emprestimo/production

**Comment by marcoayamada** [comment]
Ran Plan for project: `banking/emprestimo/production` dir: `subscriptions/banking/emprestimo` workspace: `production`

<details><summary>Show Output</summary>

```diff
Remote path --> subscriptions/banking/emprestimo

module.rg.azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/6e754131-54cf-4f48-853f-26acb5e6f5ab/resourceGroups/rg-terraform-prod]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # module.rg.azurerm_resource_group.rg has been deleted
- resource "azurerm_resource_group" "rg" {
      - id       = "/subscriptions/6e754131-54cf-4f48-853f-26acb5e6f5ab/resourceGroups/rg-terraform-prod" -> null
      - location = "brazilsouth" -> null
      - name     = "rg-terraform-prod" -> null
    }


Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.rg.azurerm_resource_group.rg will be created
+ resource "azurerm_resource_group" "rg" {
      + id       = (known after apply)
      + location = "brazilsouth"
      + name     = "rg-loans-production"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 4, in module "rg":
│    4:   providers = { azurerm = azurerm.banking-emprestimo }
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p banking/emprestimo/production`
* :put_litter_in_its_place: To **delete** this plan click [here](http://SandboxHost-637813922885942131:4141/lock?id=marcoayamada%252Fterraform-test%252Fsubscriptions%252Fbanking%252Femprestimo%252Fproduction)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p banking/emprestimo/production`
</details>

**Note: Objects have changed outside of Terraform**
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by wcavalcantevon — APPROVED** [review]

**Comment by marcoayamada** [comment]
atlantis apply

**Comment by marcoayamada** [comment]
Ran Apply for project: `banking/emprestimo/production` dir: `subscriptions/banking/emprestimo` workspace: `production`

<details><summary>Show Output</summary>

```diff
module.rg.azurerm_resource_group.rg: Creating...
module.rg.azurerm_resource_group.rg: Creation complete after 2s [id=/subscriptions/97e23b6a-9832-490d-933a-c6294936b304/resourceGroups/rg-loans-production]
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 4, in module "rg":
│    4:   providers = { azurerm = azurerm.banking-emprestimo }
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```
</details>

**Comment by marcoayamada** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by marcoayamada** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `subscriptions/banking/emprestimo` workspace: `production`

**Pull request merged**
