### PR TITLE
Feature/testonline

### PR DESCRIPTION
**Pull request by marcoayamada**

### CODE REVIEW

**Comment by marcoayamada** [comment]
atlantis plan -p banking/emprestimo/develop

**Comment by marcoayamada** [comment]
Ran Plan for project: `banking/emprestimo/develop` dir: `subscriptions/banking/emprestimo` workspace: `develop`

<details><summary>Show Output</summary>

```diff
Remote path --> subscriptions/banking/emprestimo


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.rg.azurerm_resource_group.rg will be created
+ resource "azurerm_resource_group" "rg" {
      + id       = (known after apply)
      + location = "eastus2"
      + name     = "rg-terraform-develop"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 5, in module "rg":
│    5:       azurerm = azurerm.banking-emprestimo
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p banking/emprestimo/develop`
* :put_litter_in_its_place: To **delete** this plan click [here](http://SandboxHost-637813312806890458:4141/lock?id=marcoayamada%252Fterraform-test%252Fsubscriptions%252Fbanking%252Femprestimo%252Fdevelop)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p banking/emprestimo/develop`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by marcoayamada** [comment]
**Warning**: The plan for dir: `subscriptions/banking/emprestimo` workspace: `develop` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by marcoayamada** [comment]
atlantis plan -p banking/emprestimo/develop

**Comment by marcoayamada** [comment]
Ran Plan for dir: `subscriptions/banking/emprestimo` workspace: `develop`

**Plan Error**
```
running "/atlantis/bin/terraform1.1.5 init -input=false -upgrade -backend-config=\"resource_group_name=${RG_NAME}\" -backend-config=\"storage_account_name=${STORAGE_ACCOUNT_NAME}\" -backend-config=\"container_name=${CONTAINER_NAME}\" -backend-config=\"key=${REPO_REL_DIR}\" -backend-config=\"access_key=${ARM_ACCESS_KEY}\" -reconfigure" in "/atlantis/repos/marcoayamada/terraform-test/45/develop/subscriptions/banking/emprestimo": exit status 1
Remote path --> subscriptions/banking/emprestimo

Upgrading modules...
- rg in ../../../modules/resource-group

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: blobs.Client#Get: Invalid input: `blobName` cannot be an empty string.

```

**Comment by marcoayamada** [comment]
atlantis plan -p banking/emprestimo/develop

**Comment by marcoayamada** [comment]
Ran Plan for project: `banking/emprestimo/develop` dir: `subscriptions/banking/emprestimo` workspace: `develop`

<details><summary>Show Output</summary>

```diff
Remote path --> subscriptions/banking/emprestimo


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.rg.azurerm_resource_group.rg will be created
+ resource "azurerm_resource_group" "rg" {
      + id       = (known after apply)
      + location = "eastus2"
      + name     = "rg-terraform-develop"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 5, in module "rg":
│    5:       azurerm = azurerm.banking-emprestimo
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p banking/emprestimo/develop`
* :put_litter_in_its_place: To **delete** this plan click [here](http://SandboxHost-637813312806890458:4141/lock?id=marcoayamada%252Fterraform-test%252Fsubscriptions%252Fbanking%252Femprestimo%252Fdevelop)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p banking/emprestimo/develop`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by wcavalcantevon — APPROVED** [review]
aprovado

**Comment by marcoayamada** [comment]
atlantis apply

**Comment by marcoayamada** [comment]
Ran Apply for project: `banking/emprestimo/develop` dir: `subscriptions/banking/emprestimo` workspace: `develop`

<details><summary>Show Output</summary>

```diff
module.rg.azurerm_resource_group.rg: Creating...
module.rg.azurerm_resource_group.rg: Creation complete after 0s [id=/subscriptions/2fc9aead-614d-4f91-805f-f84ea38c7410/resourceGroups/rg-terraform-develop]
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 5, in module "rg":
│    5:       azurerm = azurerm.banking-emprestimo
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```
</details>

**Comment by marcoayamada** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by marcoayamada** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `subscriptions/banking/emprestimo` workspace: `develop`

**Pull request merged**
