### PR TITLE
steve

### PR DESCRIPTION
**Pull request by marcoayamada**

### CODE REVIEW

**Comment by marcoayamada** [comment]
atlantis plan -p platform/steve/develop

**Comment by marcoayamada** [comment]
Ran Plan for project: `platform/steve/develop` dir: `subscriptions/platform/steve` workspace: `develop`

<details><summary>Show Output</summary>

```diff
Remote path --> subscriptions/platform/steve


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # module.rg.azurerm_resource_group.rg will be created
+ resource "azurerm_resource_group" "rg" {
      + id       = (known after apply)
      + location = "brazilsouth"
      + name     = "rg-steve-develop"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 4, in module "rg":
│    4:   providers = { azurerm = azurerm.platform-steve }
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p platform/steve/develop`
* :put_litter_in_its_place: To **delete** this plan click [here](http://SandboxHost-637813922885942131:4141/lock?id=marcoayamada%252Fterraform-test%252Fsubscriptions%252Fplatform%252Fsteve%252Fdevelop)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p platform/steve/develop`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by wcavalcantevon — APPROVED** [review]
aprovado

**Comment by marcoayamada** [comment]
atlantis apply

**Comment by marcoayamada** [comment]
Ran Apply for project: `platform/steve/develop` dir: `subscriptions/platform/steve` workspace: `develop`

<details><summary>Show Output</summary>

```diff
module.rg.azurerm_resource_group.rg: Creating...
module.rg.azurerm_resource_group.rg: Creation complete after 2s [id=/subscriptions/2fc9aead-614d-4f91-805f-f84ea38c7410/resourceGroups/rg-steve-develop]
╷
│ Warning: Provider azurerm is undefined
│ 
│   on main.tf line 4, in module "rg":
│    4:   providers = { azurerm = azurerm.platform-steve }
│ 
│ Module module.rg does not declare a provider named azurerm.
│ If you wish to specify a provider configuration for the module, add an
│ entry for azurerm in the required_providers block within the module.
╵

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


```
</details>

**Comment by marcoayamada** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by marcoayamada** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `subscriptions/platform/steve` workspace: `develop`

**Pull request merged**
